import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { CuratorRunReport, GitPatch, PullRequestResult } from '@curator/core';
import type { PullRequestPort } from '@curator/core';

export { GitHubPluginLockBumpService } from './plugin-lock-bump.js';

export interface GitHubConfig {
  token?: string;
  owner: string;
  repo: string;
  baseBranch: string;
}

export class GitHubPullRequestService implements PullRequestPort {
  constructor(private readonly config: GitHubConfig) {}

  async create(
    patches: GitPatch[],
    report: CuratorRunReport,
    options: { dryRun: boolean },
  ): Promise<PullRequestResult | null> {
    if (patches.length === 0) {
      return null;
    }

    const date = report.startedAt.slice(0, 10);
    const branch = `curator/${date}-${report.runId.slice(0, 8)}`;
    const title = `Improve skills using official source audit (${date})`;
    const body = buildPrBody(report, patches);

    if (options.dryRun || !this.config.token) {
      const prDir = join(process.cwd(), '.curator', 'pr-drafts');
      await mkdir(prDir, { recursive: true });
      await writeFile(
        join(prDir, `${branch}.md`),
        `# ${title}\n\n${body}\n\n## Patches\n\n${patches.map((p) => `- ${p.skill}: ${p.summary}`).join('\n')}`,
        'utf-8',
      );
      return null;
    }

    const apiBase = `https://api.github.com/repos/${this.config.owner}/${this.config.repo}`;
    const refResponse = await githubRequest<{ object: { sha: string } }>(
      `${apiBase}/git/ref/heads/${this.config.baseBranch}`,
      this.config.token,
    );

    await githubRequest(`${apiBase}/git/refs`, this.config.token, {
      method: 'POST',
      body: JSON.stringify({
        ref: `refs/heads/${branch}`,
        sha: refResponse.object.sha,
      }),
    });

    const pr = await githubRequest<{ html_url: string; number: number }>(
      `${apiBase}/pulls`,
      this.config.token,
      {
        method: 'POST',
        body: JSON.stringify({
          title,
          head: branch,
          base: this.config.baseBranch,
          body,
        }),
      },
    );

    return { url: pr.html_url, branch, number: pr.number };
  }
}

function buildPrBody(report: CuratorRunReport, patches: GitPatch[]): string {
  const lines = [
    '## Summary',
    '',
    'Automated skill improvements from LivingColor Evolution weekly audit.',
    '',
    '## Changes',
    '',
  ];

  for (const patch of patches) {
    lines.push(`- **${patch.skill}**: ${patch.summary}`);
  }

  lines.push('', '## Audit scores', '');
  for (const audit of report.audits) {
    lines.push(`- \`${audit.skill}\`: ${String(audit.score.overall_score)}/100`);
  }

  lines.push('', '## Sources', '', 'Tier-1 official sources (Symfony, Drupal, API Platform, PHP).');
  lines.push('', '---', '*Generated by [LivingColor Evolution](https://github.com/Tamsi/livingcolor-evolution)*');

  return lines.join('\n');
}

async function githubRequest<T>(
  url: string,
  token: string,
  init?: RequestInit,
): Promise<T> {
  const response = await fetch(url, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...(init?.headers ?? {}),
    },
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub API ${String(response.status)}: ${text}`);
  }

  return (await response.json()) as T;
}
